WITH CTE1 AS (SELECT 1 AS ID)
SELECT * FROM CTE1

;WITH CTE2 AS (SELECT 1 AS ID , 'Ayush' as Peer),
CTE3 AS (SELECT * FROM Employee)
SELECT * FROM CTE3


;WITH CTE2 AS (SELECT * FROM Employee WHERE GENDER LIKE '%M%'),
CTE3 AS (SELECT * FROM CTE2 WHERE Department LIKE 'D001')
SELECT * FROM CTE3